# Preprocessing

In [2]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


In [4]:
X,y = load_iris(return_X_y= True)

In [6]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [17]:
scalar = StandardScaler()
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)
X_train_scaled = scalar.fit_transform(X_train)
X_test_scaled = scalar.fit_transform(X_test)
X_train_scaled


array([[ 0.50439734, -0.7999712 ,  0.59587226,  0.72945944],
       [ 1.59389558,  0.34013027,  1.21814393,  0.72945944],
       [-0.58510091,  1.93627235, -1.44065319, -1.08877775],
       [ 0.6254527 , -0.7999712 ,  0.82215287,  0.85933353],
       [ 0.38334198, -0.57195091,  0.53930211,  0.72945944],
       [-1.06932235,  1.02419116, -1.27094274, -0.82902958],
       [-0.10087947,  2.16429264, -1.49722335, -1.34852592],
       [ 2.19917239, -1.0279915 ,  1.7272753 ,  1.37882987],
       [-0.10087947, -0.7999712 ,  0.70901257,  0.85933353],
       [-0.94826699,  0.79617087, -1.32751289, -1.34852592],
       [ 0.74650806, -0.11591032,  0.93529317,  0.72945944],
       [-1.06932235, -2.39611328, -0.19610986, -0.30953324],
       [-1.31143308,  0.79617087, -1.10123228, -1.34852592],
       [-1.31143308, -0.11591032, -1.38408304, -1.4784    ],
       [-0.22193483, -0.57195091,  0.36959166,  0.08008902],
       [ 0.26228662, -0.11591032,  0.42616181,  0.2099631 ],
       [ 0.38334198, -1.

In [18]:
import numpy as np
X_train_numpy_scaled =( X_train - np.mean(X_train, axis = 0))/np.std(X_train, axis = 0)
X_train_numpy_scaled

array([[ 0.50439734, -0.7999712 ,  0.59587226,  0.72945944],
       [ 1.59389558,  0.34013027,  1.21814393,  0.72945944],
       [-0.58510091,  1.93627235, -1.44065319, -1.08877775],
       [ 0.6254527 , -0.7999712 ,  0.82215287,  0.85933353],
       [ 0.38334198, -0.57195091,  0.53930211,  0.72945944],
       [-1.06932235,  1.02419116, -1.27094274, -0.82902958],
       [-0.10087947,  2.16429264, -1.49722335, -1.34852592],
       [ 2.19917239, -1.0279915 ,  1.7272753 ,  1.37882987],
       [-0.10087947, -0.7999712 ,  0.70901257,  0.85933353],
       [-0.94826699,  0.79617087, -1.32751289, -1.34852592],
       [ 0.74650806, -0.11591032,  0.93529317,  0.72945944],
       [-1.06932235, -2.39611328, -0.19610986, -0.30953324],
       [-1.31143308,  0.79617087, -1.10123228, -1.34852592],
       [-1.31143308, -0.11591032, -1.38408304, -1.4784    ],
       [-0.22193483, -0.57195091,  0.36959166,  0.08008902],
       [ 0.26228662, -0.11591032,  0.42616181,  0.2099631 ],
       [ 0.38334198, -1.

In [20]:
from sklearn.preprocessing import MinMaxScaler
scalar  = MinMaxScaler()
X_train_scaled = scalar.fit_transform(X_train)
X_train_scaled

array([[0.55555556, 0.29166667, 0.65517241, 0.70833333],
       [0.80555556, 0.5       , 0.84482759, 0.70833333],
       [0.30555556, 0.79166667, 0.03448276, 0.125     ],
       [0.58333333, 0.29166667, 0.72413793, 0.75      ],
       [0.52777778, 0.33333333, 0.63793103, 0.70833333],
       [0.19444444, 0.625     , 0.0862069 , 0.20833333],
       [0.41666667, 0.83333333, 0.01724138, 0.04166667],
       [0.94444444, 0.25      , 1.        , 0.91666667],
       [0.41666667, 0.29166667, 0.68965517, 0.75      ],
       [0.22222222, 0.58333333, 0.06896552, 0.04166667],
       [0.61111111, 0.41666667, 0.75862069, 0.70833333],
       [0.19444444, 0.        , 0.4137931 , 0.375     ],
       [0.13888889, 0.58333333, 0.13793103, 0.04166667],
       [0.13888889, 0.41666667, 0.05172414, 0.        ],
       [0.38888889, 0.33333333, 0.5862069 , 0.5       ],
       [0.5       , 0.41666667, 0.60344828, 0.54166667],
       [0.52777778, 0.08333333, 0.5862069 , 0.58333333],
       [0.66666667, 0.54166667,

In [21]:
X_min  = np.min(X_train, axis = 0)
X_max = np.max(X_train, axis =0)
X_train_numpy_scaled_minmax = (X_train - X_min)/(X_max - X_min)
X_train_numpy_scaled_minmax

array([[0.55555556, 0.29166667, 0.65517241, 0.70833333],
       [0.80555556, 0.5       , 0.84482759, 0.70833333],
       [0.30555556, 0.79166667, 0.03448276, 0.125     ],
       [0.58333333, 0.29166667, 0.72413793, 0.75      ],
       [0.52777778, 0.33333333, 0.63793103, 0.70833333],
       [0.19444444, 0.625     , 0.0862069 , 0.20833333],
       [0.41666667, 0.83333333, 0.01724138, 0.04166667],
       [0.94444444, 0.25      , 1.        , 0.91666667],
       [0.41666667, 0.29166667, 0.68965517, 0.75      ],
       [0.22222222, 0.58333333, 0.06896552, 0.04166667],
       [0.61111111, 0.41666667, 0.75862069, 0.70833333],
       [0.19444444, 0.        , 0.4137931 , 0.375     ],
       [0.13888889, 0.58333333, 0.13793103, 0.04166667],
       [0.13888889, 0.41666667, 0.05172414, 0.        ],
       [0.38888889, 0.33333333, 0.5862069 , 0.5       ],
       [0.5       , 0.41666667, 0.60344828, 0.54166667],
       [0.52777778, 0.08333333, 0.5862069 , 0.58333333],
       [0.66666667, 0.54166667,