In [391]:
from sklearn.datasets import load_breast_cancer
import pandas as pd

In [392]:
data = pd.read_csv('https://raw.githubusercontent.com/npradaschnor/Pima-Indians-Diabetes-Dataset/master/diabetes.csv')

In [393]:
X = data.drop('Outcome' , axis = 1)
y = data['Outcome']

In [394]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state= 42)


In [395]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter = 1000)
model.fit(X_train,y_train)

,"max_iter max_iter: int, default=100Maximum number of iterations taken for the solvers to converge.",1000
,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary <random_state>` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is '

In [396]:

y_scores =model.predict_proba(X_test)[:,1]
y_scores

array([0.2758698 , 0.18843781, 0.11448335, 0.16354256, 0.47152382,
       0.44181378, 0.01545858, 0.66077384, 0.54146156, 0.77732996,
       0.25591852, 0.89734396, 0.33619742, 0.3030328 , 0.08197907,
       0.38092474, 0.13935112, 0.0747936 , 0.8667417 , 0.5614278 ,
       0.2084072 , 0.07739223, 0.53963343, 0.09458139, 0.53950235,
       0.88554956, 0.12431156, 0.0301613 , 0.25152596, 0.11581091,
       0.91113266, 0.87075878, 0.76536338, 0.83753237, 0.6166828 ,
       0.68329681, 0.96813236, 0.24363452, 0.51147768, 0.73613319,
       0.0698326 , 0.59412031, 0.58366902, 0.32718608, 0.02758992,
       0.50239527, 0.63935312, 0.22533661, 0.36056019, 0.95629663,
       0.04889434, 0.6609671 , 0.81168271, 0.24552402, 0.09325442,
       0.04151937, 0.77816465, 0.00570348, 0.40861835, 0.75696035,
       0.74135346, 0.35193953, 0.19236342, 0.2049207 , 0.07687963,
       0.62716809, 0.05091408, 0.73285998, 0.03691782, 0.71593619,
       0.6752412 , 0.07016267, 0.18114703, 0.11429924, 0.09115

In [ ]:
from sklearn.metrics import roc_curve
fpr, tpr, thresholds = roc_curve(y_test,y_scores)

array([0.        , 0.        , 0.        , 0.01010101, 0.01010101,
       0.02020202, 0.02020202, 0.03030303, 0.03030303, 0.04040404,
       0.04040404, 0.06060606, 0.06060606, 0.07070707, 0.07070707,
       0.08080808, 0.08080808, 0.09090909, 0.09090909, 0.11111111,
       0.11111111, 0.14141414, 0.14141414, 0.17171717, 0.17171717,
       0.21212121, 0.21212121, 0.26262626, 0.26262626, 0.27272727,
       0.27272727, 0.33333333, 0.33333333, 0.35353535, 0.35353535,
       0.41414141, 0.41414141, 0.44444444, 0.44444444, 0.47474747,
       0.47474747, 0.55555556, 0.55555556, 0.5959596 , 0.5959596 ,
       0.65656566, 0.65656566, 0.8989899 , 0.8989899 , 1.        ])

In [398]:
thresholds

array([       inf, 0.9711561 , 0.96813236, 0.95629663, 0.90262603,
       0.89734396, 0.80096881, 0.77816465, 0.77790236, 0.77732996,
       0.73285998, 0.72427846, 0.68329681, 0.6752412 , 0.6609671 ,
       0.66077384, 0.6555797 , 0.64967438, 0.63935312, 0.6166828 ,
       0.60581093, 0.58366902, 0.55036131, 0.53950235, 0.53417645,
       0.50297285, 0.50239527, 0.42044451, 0.42016404, 0.40861835,
       0.38092474, 0.33903682, 0.32718608, 0.3030328 , 0.30267808,
       0.25731329, 0.24066432, 0.22533661, 0.22514667, 0.2084072 ,
       0.2049207 , 0.16354256, 0.14043021, 0.12822441, 0.12698244,
       0.11448335, 0.11429924, 0.04151937, 0.04047737, 0.00417261])

In [399]:
fpr

array([0.        , 0.        , 0.        , 0.01010101, 0.01010101,
       0.02020202, 0.02020202, 0.03030303, 0.03030303, 0.04040404,
       0.04040404, 0.06060606, 0.06060606, 0.07070707, 0.07070707,
       0.08080808, 0.08080808, 0.09090909, 0.09090909, 0.11111111,
       0.11111111, 0.14141414, 0.14141414, 0.17171717, 0.17171717,
       0.21212121, 0.21212121, 0.26262626, 0.26262626, 0.27272727,
       0.27272727, 0.33333333, 0.33333333, 0.35353535, 0.35353535,
       0.41414141, 0.41414141, 0.44444444, 0.44444444, 0.47474747,
       0.47474747, 0.55555556, 0.55555556, 0.5959596 , 0.5959596 ,
       0.65656566, 0.65656566, 0.8989899 , 0.8989899 , 1.        ])

In [400]:
tpr

array([0.        , 0.01818182, 0.03636364, 0.03636364, 0.07272727,
       0.07272727, 0.27272727, 0.27272727, 0.29090909, 0.29090909,
       0.45454545, 0.45454545, 0.50909091, 0.50909091, 0.52727273,
       0.52727273, 0.54545455, 0.54545455, 0.58181818, 0.58181818,
       0.6       , 0.6       , 0.63636364, 0.63636364, 0.65454545,
       0.65454545, 0.67272727, 0.67272727, 0.69090909, 0.69090909,
       0.70909091, 0.70909091, 0.74545455, 0.74545455, 0.76363636,
       0.76363636, 0.85454545, 0.85454545, 0.87272727, 0.87272727,
       0.89090909, 0.89090909, 0.94545455, 0.94545455, 0.96363636,
       0.96363636, 0.98181818, 0.98181818, 1.        , 1.        ])

In [401]:
import sys
print(sys.executable)

d:\scikit-learn.py\.venv\Scripts\python.exe


In [402]:
%pip install -U nbformat ipykernel notebook

Note: you may need to restart the kernel to use updated packages.


In [403]:
import plotly.graph_objects as go
import numpy as np


# Generate a trace for ROC curve 
trace0 = go.Scatter(
    x = fpr, 
    y = tpr,
    mode = 'markers+lines',
    name = 'ROC curve'
)

# Only label every nth point to avoid clusttering 
n = 10 
indices = np.arange(len(thresholds)) % n  == 0 # choose indices where index mod n is 0

trace1 = go.Scatter(
    x = fpr[indices],
    y = tpr[indices],
    mode = 'markers+text',
    name = 'Threshold points',
    text = [f"Thr = {thr:.2f}" for thr in thresholds[indices]],
    textposition = 'top center'
)


# Diagonal line 
trace2 = go.Scatter(
    x = [0,1],
    y = [0,1],
    mode = 'lines',
    name = 'Random (Area = 0.5)',
    line = dict(dash = 'dash')

)
data = [trace0, trace1, trace2]

# Define layout with square aspect ratio
layout = go.Layout(
    title = 'Receiver Operating Characteristics',
    xaxis = dict(title = 'False Positive Rate'),
    yaxis = dict(title = 'True Positive Rate'),
    autosize = False,
    width = 800,
    height = 800,
    showlegend = False
)

# Define figure and add data
fig = go.Figure(data = data, layout = layout)

# Show figure
fig.show()

In [404]:
# Assume that fpr , tpr , thresholds have already been calculated
optimal_idx = np.argmax(tpr-fpr)
optimal_threshold  = thresholds[optimal_idx]
print('Optimal threshold is: ',optimal_threshold)

Optimal threshold is:  0.5503613133055528


In [405]:
from sklearn.metrics import confusion_matrix
y1_score = (y_scores >= optimal_threshold).astype(int)
confusion_matrix(y_test, y1_score)

array([[85, 14],
       [20, 35]])

# AUC - ROC

In [406]:
from sklearn.metrics import roc_auc_score
auc1 = roc_auc_score(y_test, y_scores)
auc1

0.8128558310376492

In [407]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)


,"n_neighbors n_neighbors: int, default=5Number of neighbors to use by default for :meth:`kneighbors` queries.",5
,"weights weights: {'uniform', 'distance'}, callable or None, default='uniform'Weight function used in prediction. Possible values:- 'uniform' : uniform weights. All points in each neighborhood are weighted equally.- 'distance' : weight points by the inverse of their distance. in this case, closer neighbors of a query point will have a greater influence than neighbors which are further away.- [callable] : a user-defined function which accepts an array of distances, and returns an array of the same shape containing the weights.Refer to the example entitled:ref:`sphx_glr_auto_examples_neighbors_plot_classification.py`showing the impact of the `weights` parameter on the decisionboundary.",'uniform'
,"algorithm algorithm: {'auto', 'ball_tree', 'kd_tree', 'brute'}, default='auto'Algorithm used to compute the nearest neighbors:- 'ball_tree' will use :class:`BallTree`- 'kd_tree' will use :class:`KDTree`- 'brute' will use a brute-force search.- 'auto' will attempt to decide the most appropriate algorithm based on the values passed to :meth:`fit` method.Note: fitting on sparse input will override the setting ofthis parameter, using brute force.",'auto'
,"leaf_size leaf_size: int, default=30Leaf size passed to BallTree or KDTree. This can affect thespeed of the construction and query, as well as the memoryrequired to store the tree. The optimal value depends on thenature of the problem.",30
,"p p: float, default=2Power parameter for the Minkowski metric. When p = 1, this is equivalentto using manhattan_distance (l1), and euclidean_distance (l2) for p = 2.For arbitrary p, minkowski_distance (l_p) is used. This parameter is expectedto be positive.",2
,"metric metric: str or callable, default='minkowski'Metric to use for distance computation. Default is ""minkowski"", whichresults in the standard Euclidean distance when p = 2. See thedocumentation of `scipy.spatial.distance<https://docs.scipy.org/doc/scipy/reference/spatial.distance.html>`_ andthe metrics listed in:class:`~sklearn.metrics.pairwise.distance_metrics` for valid metricvalues.If metric is ""precomputed"", X is assumed to be a distance matrix andmust be square during fit. X may be a :term:`sparse graph`, in whichcase only ""nonzero"" elements may be considered neighbors.If metric is a callable function, it takes two arrays representing 1Dvectors as inputs and must return one value indicating the distancebetween those vectors. This works for Scipy's metrics, but is lessefficient than passing the metric name as a string.",'minkowski'
,"metric_params metric_params: dict, default=NoneAdditional keyword arguments for the metric function.",None
,"n_jobs n_jobs: int, default=NoneThe number of parallel jobs to run for neighbors search.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary <n_jobs>`for more details.Doesn't affect :meth:`fit` method.",None
Name,Type,Value
"classes_ classes_: array of shape (n_classes,)Class labels known to the classifier","ndarray[int64](2,)","[0,1]"
"effective_metric_ effective_metric_: str or callbleThe distance metric used. It will be same as the `metric` parameteror a synonym of it, e.g. 'euclidean' if the `metric` parameter set to'minkowski' and `p` parameter set to 2.",str,'eu...an'


In [417]:
y_score = knn.predict_proba(X_test)[:,1]
y_score

array([0.4, 0.4, 0. , 0.6, 0.4, 0.6, 0.2, 0.4, 0.6, 0.6, 0.2, 1. , 0.2,
       0. , 0. , 0.8, 0.2, 0. , 1. , 0.4, 0.6, 0. , 0.6, 0.2, 0.8, 1. ,
       0.2, 0. , 0.2, 0.2, 0.6, 0.4, 0.8, 1. , 0.2, 0.4, 1. , 0.4, 0.4,
       0.8, 0. , 0.8, 0.8, 0.8, 0.2, 0.4, 0.4, 0.2, 0.4, 0.6, 0. , 0.8,
       0.6, 0.2, 0.2, 0. , 0.6, 0. , 0.2, 0.6, 0.6, 0.4, 0.4, 0. , 0. ,
       0.6, 0. , 0.6, 0.2, 0.8, 0.6, 0. , 0. , 0. , 0.2, 0.6, 0.6, 0. ,
       0.4, 0.2, 0.8, 0.2, 0. , 0.4, 0.2, 1. , 0.8, 0.2, 0. , 0. , 0.2,
       0. , 0. , 0.4, 0.6, 0.6, 1. , 0. , 0.8, 0. , 0.4, 0. , 0.2, 0.6,
       0.6, 0.4, 0.4, 0.8, 0. , 0.8, 0. , 1. , 0. , 1. , 0.6, 0.4, 0.6,
       0.4, 0.2, 0.6, 0. , 0. , 0.4, 0. , 0.6, 0.6, 0. , 0.8, 0.8, 1. ,
       0.8, 0.2, 0.4, 0.6, 0.6, 0.6, 0.2, 0.6, 0.8, 0. , 0. , 0. , 0.2,
       0.8, 0.2, 0.2, 0. , 0. , 0.6, 0.8, 0. , 0. , 0.4, 0. ])

In [423]:
fpr1, tpr1, thresholds1 = roc_curve(y_test, y_score)

auc2 = roc_auc_score(y_test, y_score)
thresholds1

array([inf, 1. , 0.8, 0.6, 0.4, 0.2, 0. ])

## Plotting thresholds for both models



In [410]:
import plotly.graph_objects as go
import numpy as np

In [411]:
# Creating x-y plane and plotting thresholds for model 1
trace0 = go.Scatter(
    x = fpr,
    y = tpr, 
    mode = 'lines',
    name = f'LogisticRegression (Area: {auc1:.2f}) ',
    line = dict(color = 'blue')
)



In [412]:
# Creating x-y plane and plotting thresholds for model 2
trace2 = go.Scatter(
    x = fpr1, 
    y = tpr1,
    mode = 'lines',
    name = f'KNeighborsClassifier (Area: {auc2:.2f})',
    line = dict(color = 'green')

)

# Diagonal Line
trace4 = go.Scatter(
    x = [0,1],
    y = [0,1],
    mode = 'lines',
    line = dict(dash = 'dash'),
    name = None
)

data = [trace0 , trace2 , trace4]

# Setting Layout

layout = go.Layout(
    title = 'ROC curve comparison',
    xaxis = dict(title = 'False Positive Rate'),
    yaxis = dict(title = 'True Positive Rate'),
    autosize= False,
    width = 800,
    height= 800,
    showlegend= True
)

fig = go.Figure(data = data, layout= layout)
fig.show()